server:
  port: ${PORT:6543}
  servlet:
    context-path: /api

spring:
  datasource:
    url: ${DB_URL:${DATABASE_URL:}}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      data-source-properties:
        preferQueryMode: simple  # importante para pgBouncer do Supabase

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true

  flyway:
    enabled: false                # deixe true SE já tiver migrations em src/main/resources/db/migration
    locations: classpath:db/migration
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true
