# src/main/resources/application.yml
server:
  port: ${PORT:8080}
  forward-headers-strategy: native

spring:
  application:
    name: alexandria-api

  datasource:
    url: ${DB_URL}
    username: ${DB_USER:alexapi}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_POOL_MAX:5}
      minimum-idle: 0
      initialization-fail-timeout: -1
      data-source-properties:
        # Mantém compatibilidade com pgbouncer (Supabase pooled):
        sslmode: ${DB_SSLMODE:require}
        reWriteBatchedInserts: true
        prepareThreshold: 0

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: ${DB_SCHEMA:alexandria}
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true

  jackson:
    time-zone: America/Sao_Paulo

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: ${DB_SCHEMA:alexandria}
    table: flyway_schema_history
    baseline-on-migrate: true
    create-schemas: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

# Propriedades customizadas (ajuste conforme seu código usa)
app:
  security:
    jwt:
      secret: ${JWT_SECRET}
