server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DB_URL}       # ex: jdbc:postgresql://db.supabase.co:6543/postgres?sslmode=require
    username: ${DB_USER} # ex: alexapi
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

logging:
  level:
    org.springframework.security: INFO
    org.flywaydb: INFO

app:
  jwt:
    # gere uma chave forte (≥256 bits). Exemplo: openssl rand -base64 48
    secret: ${JWT_SECRET}
    issuer: alexandria-api
    access-token-minutes: 60
